### ISSUE TITLE
RGB Hue Shift Items

### ISSUE THREAD

**Issue by theballaam96** [2dos/DK64-Randomizer#1853]
## Easy
- [ ] Refill collectibles (ammo boxes, crystals, oranges, ...)
- [ ] Boss keys (i know this one is a :dk64lol~1: but still)
- [ ] The watermelon you shoot in minigames (#1839 )
- [ ] Shockwave charging particles
- [ ] Fairy particles
- [ ] Jetman

## Medium
- [ ] The rings you go through in vulture/owl/blast
- [ ] Fire, flames and explosions, including the rocketbarrel flames and the flame enemy
- [ ] Pads for pad moves, instruments and feeding Scoff (the blue/purple part)
- [ ] Dust particles
- [ ] Mushrooms in Forest (since that's a thing in the game)
- [ ] Jumpman

## Hard
- [ ] The DK coin you get in minigames and minecarts
- [ ] Troff and Scoff themselves (#1642 )
- [ ] And I'll keep enemies for last (I know this one is the dream and it's complicated but it would just be so cool) (#1642 )
- [ ] Kong barrels
- [ ] Lava and acid (also water maybe ?)

## Ignoring for now
- Shockwaves, from kongs and kasplats
- Pad rims (Maybe)

**Comment by AlmostSeagull** [comment]
Making a quick note here: I once noticed the Sickbay cannon's fire color not being affected. 
Also suggesting: the notes on the instrument pad rims
